### PR TITLE
fix: remove patch in favor of `skipTrailingSlashRedirect`

### PR DESCRIPTION
**Pull request by styfle**
This PR removes the patch to Next.js in favor of using the [`skipTrailingSlashRedirect`](https://nextjs.org/docs/pages/building-your-application/routing/middleware#advanced-middleware-flags) config.

This disables the automatic normalization of `href` when using `next/link` (as well as the automatic server-side redirects) in favor of manually handling the trailing slash (meaning you need to add it manually to each `href`).

### CODE REVIEW

**Comment by salazarm** [comment]
Cool this worked for me! thank you.

**Comment by styfle** [comment]
@salazarm Great, thanks!

Would you mind updating the blog post to mention this since the patch is not needed?

https://dagster.io/blog/dbt-docs-on-react

**Comment by salazarm** [comment]
Sure, btw I noticed that with SSG every prefetched page redownloads the same layout. Are there plans to optimize that?

**Comment by styfle** [comment]
Yes, there are plans to optimize that. Thanks!

**Pull request merged**
